name: Hello World Workflow

on:
  push:
    branches:
      - main  # or "master" or any branch you want

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, World!"
